iSpendApp/iSpendWebApp/Models/ReservationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using iSpendInterfaces;

namespace iSpendWebApp.Models
{
    public class ReservationViewModel:IReservation
    {
        public ReservationViewModel(IReservation reserve)
        {
            ReservationId = reserve.ReservationId;
            AccountId = reserve.AccountId;
            SavingsId = reserve.SavingsId;
            Amount = reserve.Amount;
            Date = reserve.Date;
        }

        public ReservationViewModel()
        {
            
        }

        public int ReservationId { get; set; }
        public int AccountId { get; set; }
        public int SavingsId { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        public decimal Amount { get; set; }
        public DateTime Date { get; set; }
        public IEnumerable<ISaving> UserSavings{ get; set; }
    }
}

iSpendApp/iSpendWebApp/Controllers/InvitationController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using iSpendDAL.ContextInterfaces;
using iSpendLogic;
using iSpendWebApp.Controllers.ActionFilters;
using iSpendWebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace iSpendWebApp.Controllers
{
    public class InvitationController : Controller
    {
        private readonly AccountLogic _accountLogic;
        private readonly UserLogic _userLogic;
        private readonly InvitationLogic _invitationLogic;
        public InvitationController(IAccountContext accountContext, IUserContext userContext, IInvitationContext invitationContext)
        {
            _accountLogic = new AccountLogic(accountContext);   
            _userLogic = new UserLogic(userContext);
            _invitationLogic = new InvitationLogic(invitationContext);
        }

        // GET: Invitation
        [ServiceFilter(typeof(AuthorizationActionFilter))]
        public ActionResult Index()
        {
            ViewBag.Accounts = _accountLogic.GetUserAccounts(HttpContext.Session.GetString("UserSession"));
            ViewBag.Users = _userLogic.GetAllUsers();
            var context = _invitationLogic.GetUserInvitations((int) HttpContext.Session.GetInt32("UserId"));
            var model = context.Select(invite => new InvitationViewModel(invite)).ToList();
            HttpContext.Session.SetInt32("MessageCount",model.Count);
            return View("~/Views/Invitation/Invitations.cshtml", model);
        }

        // POST: Invitation/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ServiceFilter(typeof(AuthorizationActionFilter))]
        public ActionResult Create(InvitationViewModel model)
        {
            try
            {
                model.UserIdSender = (int)HttpContext.Session.GetInt32("UserId");
                model.Date = DateTime.Now;
                _invitationLogic.CreateInvite(model);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: Invitation/Delete/5
        [ServiceFilter(typeof(AuthorizationActionFilter))]
        public ActionResult Delete(int id)
        {
            try
            {
                _invitationLogic.DeleteInvite(id);
            }
            catch
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }


        [ServiceFilter(typeof(AuthorizationActionFilter))]
        public ActionResult AcceptInvite(int id)
        {
            try
            {
                _invitationLogic.AcceptInvite(id);
            }
            catch
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

iSpendApp/iSpendWebApp/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using iSpendDAL.ContextInterfaces;
using iSpendInterfaces;
using iSpendLogic;
using iSpendWebApp.Controllers.ActionFilters;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace iSpendWebApp.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly StatisticsLogic _statisticsLogic;
        private readonly AccountLogic _accountLogic;

        public StatisticsController(IAccountContext accountContext, ITransactionContext transactionContext)
        {
            _statisticsLogic = new StatisticsLogic(accountContext, transactionContext);
            _accountLogic = new AccountLogic(accountContext);
        }

        [HttpGet]
        [ServiceFilter(typeof(AuthorizationActionFilter))]
        public IActionResult Index()
        {
            //Todo:Move logic to a logic class
            var categoryStats =
                _statisticsLogic.GetUserCategoryStatistics(HttpContext.Session.GetString("UserSession"));

            var totalBalanceStatistics =
                _statisticsLogic.GetTotalBalanceStatistics((int) HttpContext.Session.GetInt32("UserId"));

            var months = totalBalanceStatistics.MonthNumber.Select(monthNumber => DateTimeFormatInfo.CurrentInfo.GetAbbreviatedMonthName(monthNumber)).ToList();

            var accounts = _accountLogic.GetUserAccounts(HttpContext.Session.GetString("UserSession"));


            ViewBag.Categories = Newtonsoft.Json.JsonConvert.SerializeObject(categoryStats.Categories);
            ViewBag.CategoriesCosts = Newtonsoft.Json.JsonConvert.SerializeObject(categoryStats.AvgCostPerCategory);
            ViewBag.TimeStamps = Newtonsoft.Json.JsonConvert.SerializeObject(months);
            ViewBag.AccountBalance = Newtonsoft.Json.JsonConvert.SerializeObject(totalBalanceStatistics.Balances);
            ViewBag.Accounts = Newtonsoft.Json.JsonConvert.SerializeObject(accounts.Select(account => account.AccountName));
            ViewBag.BalancePerAccount = Newtonsoft.Json.JsonConvert.SerializeObject(accounts.Select(account => account.AccountBalance));

            return View("~/Views/Statistics/Dashboard.cshtml");
        }
    }
}

iSpendApp/iSpendWebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using iSpendDAL.ContextInterfaces;
using iSpendInterfaces;
using iSpendLogic;
using iSpendLogic.Models;
using iSpendWebApp.Controllers.ActionFilters;
using iSpendWebApp.Models;
using iSpendWebApp.Models.User;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace iSpendWebApp.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserContext _userContext;
        private readonly InvitationLogic _invitationLogic;

        public UserController(IUserContext userContext, IInvitationContext invitationContext)
        {
            _userContext = userContext;
            _invitationLogic = new InvitationLogic(invitationContext);
        }


        // GET: User/Login
        public ActionResult Login()
        {
            return View("Login");
        }

        //
        public ActionResult Logout()
        {
            HttpContext.Session.Remove("UserSession");
            HttpContext.Session.Remove("UserId");
            return RedirectToAction("Index", "Home");
        }

        // POST: User/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string username, string password)
        {
            var accountLogic = new UserLogic(_userContext);

            if (accountLogic.Login(username, password))
            {
                HttpContext.Session.SetString("UserSession", username);
                HttpContext.Session.SetInt32("UserId", accountLogic.GetAccountByUsername(username).UserId);
                HttpContext.Session.SetInt32("MessageCount",_invitationLogic.GetUserInvitations(accountLogic.GetAccountByUsername(username).UserId).Count());
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Login");
        }


        // GET: User/Details/5
        [ServiceFilter(typeof(AuthorizationActionFilter))]
        public ActionResult Details(int id)
        {
            var model = new UserViewModel();
            var accountLogic = new UserLogic(_userContext);
            model.Username = accountLogic.GetAccountByUsername(HttpContext.Session.GetString("UserSession")).Username;
            model.Email = accountLogic.GetAccountByUsername(HttpContext.Session.GetString("UserSession")).Email;
            return View("UserDetails", model);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View("Register");
        }

        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserViewModel model)
        {
            try
            {
                var accountLogic = new UserLogic(_userContext);
                if (ModelState.IsValid && accountLogic.IsUsernameTaken(model.Username) == false)
                {
                    accountLogic.AddUser(model.Username, model.Password, model.Email);
                    return RedirectToAction(nameof(Login));
                }
                else
                {
                    ViewBag.Message = "That username is already taken please use another.";
                    return View("Register");
                }

            }
            catch
            {
                ViewBag.Message = "Oops something went wrong please try again!";
                return View("Register");
            }
        }

        // GET: User/Edit/5
        [ServiceFilter(typeof(AuthorizationActionFilter))]
        public ActionResult Edit()
        {

            var model = new EditUserViewModel();
            var accountLogic = new UserLogic(_userContext);
            model.Username = accountLogic.GetAccountByUsername(HttpContext.Session.GetString("UserSession")).Username;
            model.Email = accountLogic.GetAccountByUsername(HttpContext.Session.GetString("UserSession")).Email;
            return View("EditUser", model);

        }

        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ServiceFilter(typeof(AuthorizationActionFilter))]
        public ActionResult Edit(EditUserViewModel model)
        {
            try
            {
                var accountLogic = new UserLogic(_userContext);
                if (ModelState.IsValid && accountLogic.IsUsernameTaken(model.Username) == false)
                {
                    model.UserId = accountLogic.GetAccountByUsername(HttpContext.Session.GetString("UserSession"))
                        .UserId;
                    accountLogic.UpdateUserDetails(model);
                    HttpContext.Session.SetString("UserSession", model.Username);
                }
                else if (accountLogic.IsUsernameTaken(model.Username) == true)
                {
                    ViewBag.Message = "That username is already taken please use another.";
                    return View("EditUser", model);
                }

                return RedirectToAction("Details");
            }
            catch
            {
                ViewBag.Message = "Oops something went wrong please try again!";
                return View("EditUser", model);
            }
        }
    }
}

iSpendApp/iSpendWebApp/Views/Shared/Overview.cshtml
@using iSpendInterfaces.Helpers
@model LandingPageViewModel

@{
    ViewData["Title"] = "BillOverview";
}

<h2>My Bills</h2>
<hr />
<div class="container">
    @if (Model.Accounts.Count == 0)
    {
        <div id="AlertBill" class="info alert-info alert-dismissible fade in">
            <a href="#AlertBill" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Quickly Get Started:</strong> To create your first account press the '+' icon!
        </div>
    }
    <row>

        @if (Model.Accounts != null)
        {
            foreach (var item in Model.Accounts)
            {
                <div class="col-sm-4 overviewCard" onclick="location.href = '@Url.Action("Index", "Transaction", new {id = item.AccountId})'">
                    <partial name="~/Views/Account/BillPartial.cshtml" model="@item" />
                </div>

            }
        }
        <div class="col-sm-4 overviewCard" style="height: 176px">
            <div align="Center">
                <div class=" panel panel-default" style="background-color: mediumseagreen; margin: 8px; font-weight: bold; color: white">
                    <div class="panel-body">
                        <div>
                            <input type="button" class="btn btn-default" value="+" onclick="location.href = '@Url.Action("Create", "Account")'" style="margin-top: 12%; margin-bottom: 13%; background-color: gray; color: white; font-weight: bold" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </row>
</div>
<hr />
<div class="container">
    <h2>My Saving Plans</h2>
    @if (Model.Savings.Count == 0)
    {
        <div id="AlertSaving" class="info alert-info alert-dismissible fade in">
            <a href="#AlertSaving" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Save money smarter:</strong> A saving plan is a smart and easy way to be more responsible with your money.
        </div>
    }
    <row>

        @if (Model.Savings != null)
        {
            foreach (var item in Model.Savings)
            {
                if (item.State == SavingState.Ongoing)
                {
                    <div class="col-sm-4 overviewCard" onclick="location.href = '@Url.Action("Details", "Savings", new {id = item.SavingId})'">
                        @{
                            <partial name="~/Views/Savings/SavingPartial.cshtml" for="@item" />
                        }
                    </div>
                }
                else if(item.State == SavingState.Completed)
                {
                    <div class="col-sm-4 overviewCard" onclick="location.href = '@Url.Action("CompleteSaving", "Savings", new {id = item.SavingId})'">
                        @{
                            <partial name="~/Views/Savings/SavingPartial.cshtml" for="@item" />
                        }
                    </div>
                }


            }
        }
        <div class="col-sm-4 overviewCard">
            <div align="Center">
                <div class=" panel panel-default" style="background-color: mediumslateblue; margin: 8px;">
                    <div class="panel-body">
                        <div>
                            <input type="button" class="btn btn-default" value="+" onclick="location.href = '@Url.Action("Create", "Savings")'" style="margin-top: 12%; margin-bottom: 13%; background-color: gray; color: white; font-weight: bold" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </row>
</div>

iSpendApp/iSpendWebApp/Views/Shared/Reservations.cshtml
@using iSpendInterfaces
@model IEnumerable<iSpendWebApp.Models.ReservationViewModel>
@{ IEnumerable<IAccount> accounts = ViewBag.Accounts;
}

<table class="table table-hover table-striped table-responsive" id="ReservationTable">
    <thead>
    <tr>
        <th>
            Account
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @if (Model != null)
    {
        foreach (var item in Model)
         {
             <tr>
                 <td>
                     @accounts.First(account => account.AccountId == item.AccountId).AccountName
                 </td>
                 <td>
                     @Html.DisplayFor(modelItem => item.Amount)
                 </td>
                 <td>
                     @item.Date.ToString("dd/MM/yyyy")
                 </td>
                 <td>                  
                     <input type="button" value="Delete" class="btn btn-danger" onclick="location.href = '@Url.Action("DeleteReservation", "Savings", new {id = item.ReservationId})'"/>
                 </td>
             </tr>
         }
    }
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $('#ReservationTable').DataTable();
    });
</script>

iSpendApp/iSpendWebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@{ var messageCount = Context.Session.GetInt32("MessageCount");
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - iSpendWebApp</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?family=Assistant" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- DataTables -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
    <!-- ToDo:include css file in project and update to my own style -->
    <link rel="stylesheet" href="css/Chart.min.css" />
    <script src="js/Chart.min.js"></script>

    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table.min.css">
    <script src="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table.min.js"></script>
    <script src="https://cdn.datatables.net/plug-ins/1.10.19/sorting/datetime-moment.js"></script>
    @*<environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>*@
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">iSpend</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index"><i class="glyphicon glyphicon-home"></i> Home</a></li>
                    @if (Context.Session.GetString("UserSession") == null)
                    {
                        <li><a asp-area="" asp-controller="User" asp-action="Create">Register</a></li>
                        <li><a asp-area="" asp-controller="User" asp-action="Login"><img src="/images/AccountIcon.svg"> Login</a></li>

                    }
                    @if (Context.Session.GetString("UserSession") != null)
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Index"><i class="glyphicon glyphicon-piggy-bank"></i> My Accounts</a></li>
                        <li><a asp-area="" asp-controller="Statistics" asp-action="Index"><i class="glyphicon glyphicon-stats"></i> Stats</a></li>
                        <li><a asp-area="" asp-controller="User" asp-action="Details"><i class="glyphicon glyphicon-user"></i> Profile</a></li>
                        <li>
                            <a asp-area="" asp-controller="Invitation" asp-action="Index">
                                <i class="glyphicon glyphicon-envelope"></i> Messages <span class="badge" style="background-color: #DC3545">@messageCount</span>
                            </a>
                        </li>
                        <li><a asp-area="" asp-controller="User" asp-action="Logout"><i class="glyphicon glyphicon-log-out "></i> Logout</a></li>
                    }
                </ul>

            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy;@DateTime.Now.Year - iSpend ©Joep Verhoeven</p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <!-- Bootstrap DatePicker-->
    <script type="text/javascript" src="~/lib/moment.js/2.9.0/Content/Scripts/moment.js"></script>
    <script type="text/javascript" src="~/lib/moment.js/2.9.0/Content/Scripts/moment-with-locales.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap.v3.datetimepicker.css/4.17.45/content/Scripts/bootstrap-datetimepicker.js"></script>

    <!-- Datatables -->
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>


    <script src="~/js/site.js" asp-append-version="true"></script>

    @*<environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>*@

    @RenderSection("Scripts", required: false)
</body>
</html>